BoYuanCore.Web/Areas/Admin/Controllers/SysRoleController.cs
using FineUICore;

using System;
using System.Collections.Generic;
using System.Linq;
using BoYuanCore.DBServices.Base;
using BoYuanCore.Entities;
using BoYuanCore.Framework.MemoryCache;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json.Linq;

namespace BoYuanCore.Web.Areas.Admin.Controllers
{
    public partial class SysRoleController : BaseController
    {
        private readonly ILogger<SysRoleController> _logger;
        private readonly ICachingProvider _iCachingProvider;

        public SysRoleController(ILogger<SysRoleController> logger, ICachingProvider iCachingProvider) : base(logger)
        {
            _logger = logger;
            _iCachingProvider = iCachingProvider;
        }

        #region ListPage
        // GET: Admin/SysRole
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowGrid(IFormCollection fc)
        {
            var keyword = fc["txb_keyword"].ToString().Trim();
            var query = DB.Select<Models.SysRoleVM>()
                .WhereIf(keyword.Length > 0, p=>p.RoleName.Contains(keyword) )
                .OrderBy(p => p.IsDel)
                .OrderBy(p => p.ID);

            var grid1 = UIHelper.Grid("Grid1");
            grid1.BindGrid(fc, "ddlPageSize", query);
            return UIHelper.Result();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BtnDelete_Click(string ids)
        {
            if (string.IsNullOrWhiteSpace(ids))
            {
                NotifyQuestion("请选择要删除的选中行！");
            }
            else
            {
                var tempStrs = ids.Substring(1).Split(',');
                List<long> idList=new List<long>();
                foreach (var str in tempStrs)
                {
                    if (long.TryParse(str.Trim(), out var idResult) && idResult!=1)//排除删除默认管理员权限角色
                    {
                        idList.Add(idResult);
                    }
                }

                if (idList.Count == 0)
                {
                    NotifyQuestion("请选择要删除的选中行！");
                }
                else
                {
                    DB.Delete<Entities.SysRole>().Where(p => idList.Contains(p.ID)).ExecuteAffrows();
                    foreach (var id in idList)
                    {
                        DBServices.SysModulePermissions.RemoveByCache(id, _iCachingProvider);
                    }
                    
                    AlertSuccess("删除成功！", false, "onGridBind()");
                }
            }
            return UIHelper.Result();
        }
        #endregion

        #region AddPage

        public ActionResult Add()
        {
            if (long.TryParse(Request.Query["id"], out long id))//编辑页面初始化
            {
                SysRole mo = FreeSqlHelper.GetModel<SysRole>(id);

                //左侧tree绑定
                ViewBag.Tree1DataSource = CreateTree(id).ToArray();
                mo.IsDel = !mo.IsDel;
                return View(mo);
            }
            else //添加页面
            {
                //左侧tree绑定
                ViewBag.Tree1DataSource = CreateTree().ToArray();
                ViewBag.isJsAdd = 1;//
                return View();//添加页面
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BtnSave_OnClick(IFormCollection fc)
        {
            string nodeStr = fc["checkedNodes"];
            if (string.IsNullOrEmpty(nodeStr))
            {
                NotifyQuestion("请选择权限");
                return UIHelper.Result();
            }

            bool isEdit = long.TryParse(fc["f_ID"], out long ID);

            BoYuanCore.Entities.SysRole mo = new BoYuanCore.Entities.SysRole();
            mo.IsDel = !Convert.ToBoolean(fc["f_IsDel"]);
            mo.Remark = fc["f_Remark"];
            mo.RoleName = fc["f_RoleName"];


            string[] nodes = nodeStr.Substring(1).Split(',');
            List<SysModulePermissions> permissionsList = new List<SysModulePermissions>();

            if (!isEdit)//添加
            {
                var roleId = FreeSqlHelper.InsertModel(mo);
                if (roleId > 0)
                {
                    //页面关系
                    permissionsList.AddRange(nodes.Select(t => new SysModulePermissions() { PageID = Convert.ToInt64(t), RoleID = roleId }));
                    DB.Insert(permissionsList).ExecuteAffrows();
                    DBServices.SysModulePermissions.RemoveByCache(roleId, _iCachingProvider);

                    AlertInfor("添加成功", true);
                }
                else
                {
                    NotifyError("添加失败");
                }
            }
            else//修改
            {
                mo.ID = ID;
                int returnNum = FreeSqlHelper.UpdateModels(mo, p => new { p.IsDel, p.RoleName,p.Remark });
                if (returnNum > 0)
                {
                    //页面关系
                    DB.Delete<Entities.SysModulePermissions>().Where(p => p.RoleID == mo.ID).ExecuteAffrows();//删除旧的数据
                    permissionsList.AddRange(nodes.Select(t => new SysModulePermissions() { PageID = Convert.ToInt64(t), RoleID = mo.ID }));
                    DB.Insert(permissionsList).ExecuteAffrows();
                    DBServices.SysModulePermissions.RemoveByCache(mo.ID, _iCachingProvider);

                    AlertInfor("修改成功", true);
                }
                else
                {
                    NotifyError("修改失败");
                }
            }
            return UIHelper.Result();
        }
        #endregion

        #region tree
        /// <summary>
        /// 绑定tree
        /// </summary>
        /// <returns></returns>
        public static IList<TreeNode> CreateTree(long roleId = 0)
        {
            List<long> pageList = null;
            if (roleId > 0)
                pageList = DB.Select<SysModulePermissions>().Where(p => p.RoleID == roleId).ToList(p => p.PageID);

            var moduleList = DB.Select<SysModule>().WhereIf(!HaveButtonPermissions, p => string.IsNullOrEmpty(p.ButtonID)).ToList();
            IList<TreeNode> nodes = new List<TreeNode>();
            var mainNode = new TreeNode() {NodeID = "0", Text = "全选", Expanded = true};

            CreateTreeNodes(moduleList, mainNode, pageList);
            nodes.Add(mainNode);

            return nodes;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="moduleList"></param>
        /// <param name="parentNode"></param>
        public static void CreateTreeNodes(List<SysModule> moduleList, TreeNode parentNode, List<long> pageList)
        {
            var list = moduleList.Where(p => p.ParentID.ToString() == parentNode.NodeID).OrderBy(p => p.Sort).ToList();

            if (list == null || list.Count == 0) return;

            TreeNode node;
            foreach (var module in list)
            {
                node = new TreeNode();

                node.NodeID = module.ID.ToString();

                if (string.IsNullOrEmpty(module.ButtonID))//page 或 folder
                {
                    node.Text = module.PageTitle + (module.Remark.Length > 0 ? "(" + module.Remark + ")" : string.Empty) +
                                (module.IsHidden ? "<font color='red'>不显示</font>" : string.Empty);

                    if (!string.IsNullOrEmpty(module.Icon)) node.IconUrl = "/" + module.Icon;
                    if (!string.IsNullOrEmpty(module.FontIcon)) node.IconFont = (IconFont)Enum.Parse(typeof(IconFont), module.FontIcon);
                }
                else //button
                {
                    node.Text = "<font color='blue'>按钮</font> " + module.ButtonText + "(" + module.ButtonID + ")" +
                                (module.IsHidden ? "<font color='red'>不显示</font>" : string.Empty);
                    node.IconFont = IconFont.MousePointer;
                }

                node.Expanded = true;//默认节点都为展开

                if (pageList != null)
                    node.Checked = pageList.Contains(module.ID);

                CreateTreeNodes(moduleList, node, pageList);
                parentNode.Nodes.Add(node);
            }
        }


        #endregion
    }
}

BoYuanCore.Web/Areas/Admin/Views/SysRole/Add.cshtml
@{
    ViewBag.Title = "编辑页面";
    var F = Html.F();
}

@model BoYuanCore.Entities.SysRole

@section head {

}

@section body {
    @(
    F.Tree().ID("Tree1").Width(650).EnableCollapse(false).ShowHeader(false).EnableCheckBox(true).IsViewPort(true)
        .Nodes((TreeNode[])ViewBag.Tree1DataSource).Listener("nodecheck", "onTreeNodeCheck")
        .Toolbars(
            F.Toolbar().Items(
                F.TextBoxFor(m => m.RoleName).ID("f_RoleName").Label("权限角色名称").LabelWidth(120).ShowRedStar(true).Required(true)
                ,F.CheckBoxFor(m=>m.IsDel).ID("f_IsDel").ShowLabel(false).DisplayType(CheckBoxDisplayType.Switch).SwitchTextVisible(true).SwitchOnText("启用").SwitchOffText("不可用").Width(70)
                ,F.Button().ID("Button_add").Icon(Icon.TableEdit).Text("保存权限角色").OnClientClick("AddInfo()").ValidateForms("Tree1")
                    ,F.HiddenFieldFor(m=>m.ID).ID("f_ID")
                ),
            F.Toolbar().Items(
                    F.TextBoxFor(m => m.Remark).ID("f_Remark").Label("备注").MaxLength(200).LabelWidth(120).Width(500)
                )
        )


    )
}

@section script {
    <script>
        F.ready(function () {
           @if (ViewBag.isJsAdd != null)
           {
               @Html.Raw("F.ui.f_IsDel.setValue(true);")
           }
        })

        function AddInfo() {
            F.doPostBack('@Url.Action("BtnSave_OnClick")', "Tree1",{ checkedNodes:getCheckedNodes()});
        }

        function onTreeNodeCheck(event, nodeId, checked) {
            var me = this;
            F.noEvent(function () {
                if (checked) {
                    // 第二个参数true：递归更新全部子节点
                    me.checkNode(nodeId, true);
                } else {
                    me.uncheckNode(nodeId, true);
                }
            });
        }

        function getCheckedNodes() {
            var result = '';
            var checkedNodes = F.ui.Tree1.getCheckedNodes(true);
            if (checkedNodes.length) {
                $.each(checkedNodes, function (index, node) {
                    result += "," + node.id;
                });
            }
            return result;
        }

    </script>
}

BoYuanCore.Web/Areas/Admin/Views/SysRole/Index.cshtml
@{
    ViewBag.Title = "列表";
    var F = Html.F();
}

@section head {

}

@section body {
    @(F.Panel().ID("Panel1").BodyPadding(3).ShowBorder(false).ShowHeader(false).Layout(LayoutType.Fit).AutoScroll(true).IsViewPort(true)
        .Toolbars(F.Toolbar().Position(ToolbarPosition.Top).Items(
                F.Button().ID("BtnAdd").Icon(Icon.Add).Text("新增").OnClientClick("openWindow()"),
                F.ToolbarSeparator(),
                F.Button().ID("BtnDelete").Icon(Icon.Delete).Text("批量删除").OnClientClick("DeleteRows()"))
            )
            .Items(
                F.Grid().Layout(LayoutType.Fit).AllowPaging(true).IsDatabasePaging(true).EnableCheckBoxSelect(true).CheckBoxSelectOnly(true).ShowHeader(false).ShowBorder(true)
                .ID("Grid1").Listener("paging", "onGridBind").DataIDField("GridID").EnableTextSelection(true).EnableHeaderMenu(false)
                .Toolbars(F.Toolbar().Position(ToolbarPosition.Top)
                    .Items(
                        F.TextBox().ID("txb_keyword").EmptyText("权限名称查询"),
                        F.Button().ID("BtnSearch").Text("查询").Icon(Icon.SystemSearch).OnClientClick("onGridBind()")
                    )
            )
            .PageItems(
                F.ToolbarSeparator(),
                F.DropDownList().ID("ddlPageSize").Width(160).Label("每页记录数")
                    .Items(
                        F.ListItem().Text("10").Value("10"),
                        F.ListItem().Text("20").Value("20").Selected(true),
                        F.ListItem().Text("50").Value("50"),
                        F.ListItem().Text("100").Value("100")
                    ),
                F.ToolbarSeparator()
            )
            .Columns(
                //F.RowNumberField(),
                F.RenderField().HeaderText("编辑").ColumnID("Actions").Width(50).RendererFunction("renderActions")
                ,F.RenderField().HeaderText("权限名称").DataField("RoleName").Width(200)
                ,F.RenderField().HeaderText("备注").DataField("Remark").Width(200).ExpandUnusedSpace(true)
                , F.RenderCheckField().HeaderText("显示").DataField("State").RenderAsStaticField(true).Width(70)

            )
    ))
    @(F.Window().ID("Window1").Height(500).Width(700).IsModal(true).EnableMaximize(true).EnableIFrame(true).Hidden(true).Icon(Icon.ApplicationFormEdit).Target(Target.Top).EnableResize(true)
        .CloseAction(CloseAction.HidePostBack).Listener("close", "onGridBind"))
}

@section script {
    <script>
        function onGridBind(event, pageindex,oldPageIndex) {
            var grid1 = F.ui.Grid1;
            if (!pageindex) pageindex=0;
            grid1.setPageIndex(pageindex);
            // 触发后台事件
            F.doPostBack('@Url.Action("ShowGrid")', "Panel1");
        }

        F.ready(function() {
            onGridBind();
            F.ui.ddlPageSize.on('change', function () { onGridBind() });

            var grid = F.ui.Grid1;
            grid.el.on('click', 'a.action', function (event) {
                var cnode = $(this);
                var rowEl = cnode.closest('.f-grid-row');
                var rowData = grid.getRowData(rowEl);
                var rowId = rowData.id;

                if (cnode.hasClass('editit')) {
                    openWindow(rowId); // 编辑窗体
                }
            });
        })

        function DeleteRows() {
            var result = '', grid = F.ui.Grid1;
            var selectRows = grid.getSelectedRows(true);
            if (selectRows.length == 0) {
                NotifyQuestion("请选择要删除的选中行");
                return;
            }
            F.confirm({
                message: "确定要执行选中行删除操作吗？",
                ok: function() {                   
                    $.each(selectRows,
                        function(index, item) {
                            result += ',' + item.id; // item.id对应绑定的.DataIDField("GridID")的值;item.values.字段1 对应列DataField("字段1")
                        });
                    F.doPostBack('@Url.Action("BtnDelete_Click")', { ids: result });                    
                }
            })
        }

        function openWindow(id) {
            var url = '@Url.Action("Add", "SysRole")';
            if (id) {
                F.ui.Window1.show(url+'?id='+id, '编辑');
            } else {
                F.ui.Window1.show(url, '新增');
            }
        }
    </script>
}