BoYuanCore.Web/Areas/Admin/Controllers/SysAdminController.cs
using FineUICore;

using System;
using System.Collections.Generic;
using System.Linq;
using BoYuanCore.DBServices.Base;
using BoYuanCore.Framework;
using BoYuanCore.Framework.MemoryCache;
using BoYuanCore.Framework.Net;
using BoYuanCore.WebUI.Code.Filter;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.FileProviders;
using Microsoft.Extensions.Logging;

namespace BoYuanCore.Web.Areas.Admin.Controllers
{
    public partial class SysAdminController : BaseController
    {
        private readonly ILogger<SysAdminController> _logger;
        private readonly ICachingProvider _iCachingProvider;

        public SysAdminController(ILogger<SysAdminController> logger, ICachingProvider iCachingProvider) : base(logger)
        {
            _logger = logger;
            _iCachingProvider = iCachingProvider;
        }

        #region ListPage
        // GET: Admin/SysAdmin
        public ActionResult Index()
        {
            var list= DB.Select<Entities.SysRole>().Where(p => p.IsDel == false).ToList(p => new { p.RoleName, GridID= p.ID.ToString() });
            list.Insert(0,new {RoleName="全部",GridID="%"});
            ViewBag.role = list;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ShowGrid(IFormCollection fc)
        {
            var grid1 = UIHelper.Grid("Grid1");
            int pageSize = int.Parse(fc["ddlPageSize"]);
            string keyword = fc["txb_keyword"].ToString().Trim();
          
            var dataList = DB.Select<Entities.SysAdmin,Entities.SysRole>()
                .LeftJoin((a,r)=>a.RoleID==r.ID)
                .WhereIf(keyword.Length > 0, (a, r) => a.RealName.Contains(keyword) || a.LoginName.Contains(keyword))
                .WhereIf(long.TryParse(fc["f_RoleID"].ToString(),out var roleResult), (a, r) => a.RoleID==roleResult)
                .OrderBy((a, r) => a.ID)
                .Count(out var recordCount).Page(int.Parse(fc[grid1.Source.ID + "_pageIndex"]) + 1, pageSize)
                .ToList((a, r)=>new Models.SysAdminVM());

            grid1.BindGrid(dataList, fc, pageSize, (int) recordCount);

            return UIHelper.Result();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Button_delete_Click(string ids)
        {
            if (string.IsNullOrWhiteSpace(ids))
            {
                NotifyQuestion("请选择要删除的选中行！");
            }
            else
            {
                var tempStrs = ids.Substring(1).Split(',');
                List<long> idList = new List<long>();
                foreach (var str in tempStrs)
                {
                    if (long.TryParse(str.Trim(), out var idResult) && idResult != 1)//排除删除默认管理员
                    {
                        idList.Add(idResult);
                    }
                }
                if (idList.Count == 0)
                {
                    NotifyQuestion("请选择要删除的选中行！");
                }
                else
                {
                    DB.Delete<Entities.SysAdmin>().Where(p => idList.Contains(p.ID)).ExecuteAffrows();
                    foreach (var id in idList)
                    {
                        DBServices.SysAdmin.RemoveCache(id, _iCachingProvider);//更新缓存
                    }
                    AlertSuccess("删除成功！", false, "onGridBind()");
                }
            }
            return UIHelper.Result();
        }
        #endregion

        #region AddPage

        public ActionResult Add()
        {
            ViewBag.role = DB.Select<Entities.SysRole>().Where(p => p.IsDel == false).ToList(p=>new {p.RoleName, GridID = p.ID.ToString()});

            if (long.TryParse(Request.Query["id"], out long id))//编辑页面初始化
            {
                Entities.SysAdmin mo = DBServices.SysAdmin.GetAdminByCache(id, _iCachingProvider); ;
                ViewBag.haveUpdate = 1;
                return View(mo);
            }
            return View();//添加页面
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Button_save_OnClick(IFormCollection fc)
        {
            bool isEdit = long.TryParse(fc["f_ID"], out long ID);
            if (!isEdit) //添加
            {
                if (string.IsNullOrEmpty(fc["f_Password"]))
                {
                    NotifyQuestion("请设置密码!");
                    return UIHelper.Result();
                }
            }

            bool haveLoginName = DB.Select<Entities.SysAdmin>()
                .WhereIf(isEdit,p=>p.ID!=ID)
                .Where(p => p.LoginName == fc["f_LoginName"]).Any();
            if (haveLoginName)
            {
                NotifyError("登录名称重复请换个！");
                return UIHelper.Result();
            }

            Entities.SysAdmin mo = new Entities.SysAdmin();
            mo.LoginName = fc["f_LoginName"];
            mo.RealName = fc["f_RealName"];
            if (long.TryParse(fc["f_RoleID"], out var RoleIDTempResult)) mo.RoleID = RoleIDTempResult;
            mo.Remark = fc["f_Remark"];
            mo.Photo =string.Empty;
            if (int.TryParse(fc["f_Sort"], out var SortTempResult)) mo.Sort = SortTempResult;
            mo.IsDel = Convert.ToBoolean(fc["f_IsDel"]);

            if (!isEdit)//添加
            {
                mo.Password = Security.MD5Helper.GetMd5Pwd(fc["f_Password"]);

                if (FreeSqlHelper.InsertModel(mo) > 0)
                {
                    AlertInfor("添加成功", true);
                }
                else
                {
                    NotifyError("添加失败");
                }
            }
            else//修改
            {
                mo.ID = ID;
                int returnNum = 0;

                if (string.IsNullOrEmpty(fc["f_Password"]))
                {
                    returnNum = FreeSqlHelper.UpdateModels(mo,
                        p => new { p.LoginName, p.RealName, p.RoleID, p.Remark, p.Photo, p.Sort, p.IsDel });
                }
                else //更改密码
                {
                    mo.Password = Security.MD5Helper.GetMd5Pwd(fc["f_Password"]);
                    returnNum = FreeSqlHelper.UpdateModels(mo,
                        p => new { p.LoginName, p.RealName, p.RoleID,p.Password, p.Remark, p.Photo, p.Sort, p.IsDel });
                }

                if (returnNum > 0)
                {
                    DBServices.SysAdmin.RemoveCache(mo.ID, _iCachingProvider);//更新缓存
                    AlertInfor("修改成功", true);
                }
                else
                {
                    NotifyError("修改失败");
                }
            }
            return UIHelper.Result();
        }

        #endregion
    }
}

BoYuanCore.Web/Areas/Admin/Views/SysAdmin/Add.cshtml
@{
    ViewBag.Title = "编辑页面";
    var F = Html.F();
}

@model BoYuanCore.Entities.SysAdmin

@section head {

}

@section body {
    @(F.Form().ID("form_Edit").ShowHeader(false).ShowBorder(false).AutoScroll(true).BodyPadding("15px 15px").IsViewPort(true)
        .Rows(
            F.FormRow().Items(F.TextBoxFor(m=>m.LoginName).ID("f_LoginName").Label("登录名称").Required(true).ShowRedStar(true).MaxLength(25))
            ,F.FormRow().Items(F.TextBoxFor(m=>m.RealName).ID("f_RealName").Label("真实姓名").MaxLength(30))
            ,F.FormRow().Items(F.TextBox().ID("f_Password").Label("密码").TextMode(TextMode.Password).EmptyText("注意:输入后可直接修改密码"))
            ,F.FormRow().Items(F.DropDownListFor(m => m.RoleID).ID("f_RoleID").DataTextField("RoleName").DataValueField("GridID").Label("权限角色").DataSource(ViewBag.role))
            ,F.FormRow().Items(F.TextBoxFor(m=>m.Remark).ID("f_Remark").Label("备注").MaxLength(500))
            ,F.FormRow().Items(F.NumberBoxFor(m=>m.Sort).ID("f_Sort").Label("排序").NoDecimal(true))
            ,F.FormRow().Items(F.CheckBoxFor(m=>m.IsDel).ID("f_IsDel").Label("显示").DisplayType(CheckBoxDisplayType.Switch).SwitchTextVisible(true).SwitchOnText("删除").SwitchOffText("正常"))


        )
        .Toolbars(F.Toolbar().Position(ToolbarPosition.Bottom)
            .Items(F.HiddenFieldFor(m=>m.ID).ID("f_ID"), F.ToolbarFill(),
                F.Button().ID("Button_save").ValidateForms("form_Edit").Text("保存").Icon(Icon.SystemSaveNew).OnClick(Url.Action("Button_save_OnClick"),"form_Edit")
            )
        ))
}

@section script {
     <script>
        F.ready(function () {
            @if(ViewBag.haveUpdate == null)
            {
                @Html.Raw("F.ui.f_RoleID.setValue('0');");
                @Html.Raw("F.ui.f_Sort.setValue('1000');");
            }
        })
     </script>
}

BoYuanCore.Web/Areas/Admin/Views/SysAdmin/Index.cshtml
@{
    ViewBag.Title = "列表";
    var F = Html.F();
}

@section head {

}

@section body {
    @(F.Panel().ID("Panel1").BodyPadding(3).ShowBorder(false).ShowHeader(false).Layout(LayoutType.Fit).AutoScroll(true).IsViewPort(true)
        .Toolbars(F.Toolbar().Position(ToolbarPosition.Top).Items(
            F.Button().ID("Button_add").Icon(Icon.Add).Text("新增").OnClientClick("openWindow()"),
            F.ToolbarSeparator(),
            F.Button().ID("Button_delete").Icon(Icon.Delete).Text("批量删除").OnClientClick("getGridSelectedRows()"))
        )
        .Items(
            F.Grid().Layout(LayoutType.Fit).AllowPaging(true).IsDatabasePaging(true).EnableCheckBoxSelect(true).CheckBoxSelectOnly(true).ShowHeader(false).ShowBorder(true)
                .ID("Grid1").OnPageIndexChanged(Url.Action("ShowGrid"),"Panel1").DataIDField("GridID").EnableTextSelection(true).EnableHeaderMenu(false)
                .Toolbars(F.Toolbar().Position(ToolbarPosition.Top)
                    .Items(
                        F.DropDownList().ID("f_RoleID").DataTextField("RoleName").DataValueField("GridID").Label("权限角色").DataSource(ViewBag.role),
                        F.TextBox().ID("txb_keyword").EmptyText("登录名称或真实姓名查询"),
                        F.Button().ID("btnSearch").Text("查询").Icon(Icon.SystemSearch).OnClientClick("onGridBind()")
                    )
                )
                .PageItems(
                    F.ToolbarSeparator(),
                    F.DropDownList().ID("ddlPageSize").Width(160).Label("每页记录数")
                        .Items(
                            F.ListItem().Text("10").Value("10"),
                            F.ListItem().Text("20").Value("20").Selected(true),
                            F.ListItem().Text("50").Value("50"),
                            F.ListItem().Text("100").Value("100")
                        ),
                    F.ToolbarSeparator()
                )
                .Columns(
                    //F.RowNumberField(),
                    F.RenderField().HeaderText("编辑").ColumnID("Actions").Width(50).RendererFunction("renderActions")
                    ,F.RenderField().HeaderText("登录名称").DataField("LoginName").Width(100)
                    ,F.RenderField().HeaderText("真实姓名").DataField("RealName").Width(100)
                    ,F.RenderField().HeaderText("权限角色").DataField("RoleName").Width(150)
                    ,F.RenderField().HeaderText("照片").DataField("Photo").Width(100).RendererFunction("renderPhoto").HeaderTextAlign(TextAlign.Center)
                    , F.RenderField().HeaderText("排序").DataField("Sort").FieldType(FieldType.Int).TextAlign(TextAlign.Right).Width(70)
                    ,F.RenderField().HeaderText("备注").DataField("Remark").Width(100).ExpandUnusedSpace(true)
                    ,F.RenderCheckField().HeaderText("显示").DataField("State").RenderAsStaticField(true).Width(50)

                )
        ))
    @(F.Window().ID("Window1").Height(450).Width(650).IsModal(true).EnableMaximize(true).EnableIFrame(true).Hidden(true).Icon(Icon.ApplicationFormEdit).Target(Target.Top).EnableResize(true)
        .CloseAction(CloseAction.HidePostBack).OnClose(Url.Action("ShowGrid"),"Panel1"))
}

@section script {
    <script>
        function onGridBind() {
            var grid1 = F.ui.Grid1;
            grid1.setPageIndex(0);
            // 触发后台事件
            F.doPostBack('@Url.Action("ShowGrid")', "Panel1");
        }

        F.ready(function() {
            onGridBind();
            F.ui.ddlPageSize.on('change', function () { onGridBind() });

            var grid = F.ui.Grid1;
            grid.el.on('click', '.f-grid-cell-Actions .action.editit', function (event) {
                var targetEl = $(this);
                var rowEl = targetEl.closest('.f-grid-row');
                var rowData = grid.getRowData(rowEl);
                var rowId = rowData.id;
                openWindow(rowId); // 显示窗体
            });
        })

        function getGridSelectedRows() {
            F.confirm({
                message: "确定要执行选中行删除操作吗？",
                ok: function() {
                    var result = '', grid = F.ui.Grid1;                  
                    var selectRows = grid.getSelectedRows(true);
                    if (selectRows.length == 0) {
                        NotifyQuestion("请选择要删除的选中行");
                    }
                    else {
                        $.each(selectRows,
                            function (index, item) {
                                result += ',' + item.id;// item.id对应绑定的.DataIDField("GridID")的值;item.values.字段1 对应列DataField("字段1")
                            });
                        F.doPostBack('@Url.Action("Button_delete_Click")', { ids: result });
                    }
                }
            })
        }

        function openWindow(id) {
            if (id) {
                F.ui.Window1.show('@Url.Action("Add", "SysAdmin")'+"?id="+id, '编辑');
            } else {
                F.ui.Window1.show('@Url.Action("Add")', '新增');
            }
        }

        function renderPhoto(value, params) {
            return GetHtmlImg(value,"","","width='80'");
        }
    </script>
}